<a href="https://colab.research.google.com/github/King-of-Comets/generative-ai-for-beginners/blob/main/aiBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORTS

In [2]:
import torch
import numpy as np

# Python Lists

In [14]:
my_list = [[1,2,3,4,5], [6,7,8,9,19]]
my_list
type(my_list[0][0])

int

# Numpy Arrays

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.18086512, 0.23826857, 0.99947867, 0.93975068],
       [0.80695533, 0.4813589 , 0.89325682, 0.75807984],
       [0.90122847, 0.36936969, 0.89021714, 0.42319575]])

In [5]:
np1.dtype

dtype('float64')

# Tensors

In [17]:
tensor_2d = torch.randn(3,4)
tensor_2d.dtype

torch.float32

In [19]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.1631,  0.3680, -2.3475,  0.1441],
         [ 0.5165, -0.0501,  0.9500,  1.0857],
         [ 0.2567,  0.1649,  0.6273, -1.0115]],

        [[ 0.2180, -0.5656, -0.3237, -0.1192],
         [ 0.8154,  0.8798,  0.1177, -0.0698],
         [-1.1246, -0.1886,  0.2322, -0.2367]]])

In [23]:
# create tensor out of array
my_tensor = torch.tensor(np1, dtype=torch.float32)
my_tensor

tensor([[0.1809, 0.2383, 0.9995, 0.9398],
        [0.8070, 0.4814, 0.8933, 0.7581],
        [0.9012, 0.3694, 0.8902, 0.4232]])